source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/cppfw/cocoapods-repo.git'

project 'basic/basic.xcodeproj'

target "basic" do
	pod 'libutki', '>= 1.0.21'
	pod 'libruisapp', '>= 0.1.4'
	pod 'libruis', '>= 0.4.12'
end
