#pragma once

#include <utki/config.hpp>



#define M_MORDAVOKNE_RENDER_OPENGL			0
#define M_MORDAVOKNE_RENDER_OPENGLES		1
#define M_MORDAVOKNE_RENDER_DIRECTX			2


#if M_OS == M_OS_LINUX

#	if M_OS_NAME == M_OS_NAME_ANDROID
#		define M_MORDAVOKNE_RENDER M_MORDAVOKNE_RENDER_OPENGLES
#	else
#		define M_MORDAVOKNE_RENDER M_MORDAVOKNE_RENDER_OPENGL
#	endif

#elif M_OS == M_OS_WINDOWS

#	ifdef M_MORDA_ENFORCE_DIRECTX_UNDER_WINDOWS
#		define M_MORDAVOKNE_RENDER M_MORDAVOKNE_RENDER_DIRECTX
#	else
#		define M_MORDAVOKNE_RENDER M_MORDAVOKNE_RENDER_OPENGL
#	endif

#elif M_OS == M_OS_MACOSX

#	if M_OS_NAME == M_OS_NAME_IOS
#		define M_MORDAVOKNE_RENDER M_MORDAVOKNE_RENDER_OPENGLES
#	else
#		define M_MORDAVOKNE_RENDER M_MORDAVOKNE_RENDER_OPENGL
#	endif

#else
#	error "unknown OS"
#endif

