source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/igagis/cocoapods-repo.git'

target "tests" do
	pod 'libutki', '>= 1.0.32'
	pod 'libpapki', '>= 1.0.3'
	pod 'libkolme', '>= 1.0.1'
	pod 'libstob', '>= 3.1.1'
	pod 'libmorda', '>= 0.4.4'
	pod 'libmorda-opengles2-ren', '>= 0.1.7'
end
