source 'https://github.com/cppfw/cocoapods-repo.git'

project 'mordavokne/mordavokne.xcodeproj'

# TODO: make 11.0 ?
platform :ios, '13.0'

target "mordavokne" do
	pod 'utki', '>= 1.1.124'
	pod 'papki', '>= 1.0.93'
	pod 'r4', '>= 0.1.53'
	pod 'treeml', '>= 0.1.28'
	pod 'morda', '>= 0.5.195'
	pod 'morda-render-opengles', '>= 0.1.37'
end
