source 'https://github.com/cppfw/cocoapods-repo.git'

project 'mordavokne/mordavokne.xcodeproj'

platform :ios, '8.0'

target "mordavokne" do
	pod 'utki', '>= 1.1.112'
	pod 'papki', '>= 1.0.91'
	pod 'r4', '>= 0.1.51'
	pod 'puu', '>= 0.1.25'
	pod 'morda', '>= 0.5.159'
	pod 'morda-opengles2-ren', '>= 0.1.35'
end
